snowflake_project:
  outputs:
    dev:
      account: ug73390.us-east-2.aws
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
  send_anonymous_usage_stats: False