# Nazwa projektu dbt
name: 'project'
version: '1.0.0'

# Ustawienie profilu dbt
profile: 'project'

# Ścieżki do różnych zasobów w projekcie
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Katalogi do czyszczenia przez `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

models:
  project:
    +persist_docs:
      relation: true  # Przechowuje opis tabeli w BigQuery
      columns: true   # Przechowuje opisy kolumn w BigQuery
    +materialized: table  # Ustawienie materializacji jako tabela