# Nazwa projektu dbt - powinna zawierać tylko małe litery i podkreślenia
# Powinna odzwierciedlać organizację lub przeznaczenie projektu
name: 'project'

# Wersja projektu - pozwala na zarządzanie wersjami konfiguracji
version: '1.0.0'

# Wersja konfiguracji dbt - aktualnie obsługiwana wersja to 2
config-version: 2

# Określa, który profil dbt zostanie użyty do połączenia z bazą danych
profile: 'dev'

# Ścieżki do różnych typów plików w projekcie dbt
model-paths: ["models"]         # Katalog, w którym znajdują się modele SQL
analysis-paths: ["analyses"]     # Katalog na analizy ad hoc w SQL
test-paths: ["tests"]            # Katalog na testy dbt
seed-paths: ["seeds"]            # Katalog na pliki CSV (seed data)
macro-paths: ["macros"]          # Katalog na makra dbt
snapshot-paths: ["snapshots"]    # Katalog na snapshoty historyczne

# Katalog, w którym dbt zapisuje skompilowane pliki SQL i wyniki
target-path: "target"

# Określa katalogi, które zostaną usunięte przez `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Na początku każdego procesu dbt zostanie uruchomione makro get_brand_name()
# (zdefiniowane w macros/macro_get_brand_name.sql). Tworzy ono funkcję użytkownika (UDF)
# w schemacie w BigQuery.
on-run-start:
  - "{{ get_brand_name() }}"  # Automatyczne uruchomienie makra na starcie

# Konfiguracja domyślnego zachowania dla modeli w projekcie
models:
  project:
    +materialized: table  # Domyślna materializacja to tabela (table)
    +persist_docs:        # Zapisuje opisy kolumn w bazie danych (np. BigQuery)
      relation: true
      columns: true
  +hours_to_expiration: 168  # Table deletes 168 hours (7 days) after creation
  +model_versioning: true  # Włącza wersjonowanie modeli


# Konfiguracja domyślna dla testów w projekcie
tests:
  project:
    +severity: warn  # Wszystkie testy domyślnie ustawione jako ostrzeżenie (warn)

  marts: # Model zarządzania - group
    sales:
      +group: sales # Model zarządzania - group
    marketing:
      +group: marketing # Model zarządzania - group