dev:
  target: dev
  outputs:
    dev:
      dataset: dbt_dev_project
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/pmackowka/Documents/sa/dbt-project.json
      location: US
      method: service-account
      priority: interactive
      project: coral-shift-440513-f3
      threads: 64
      type: bigquery

    prod:
      dataset: dbt_prod_project
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/pmackowka/Documents/sa/dbt-project.json
      location: US
      method: service-account
      priority: interactive
      project: coral-shift-440513-f3
      threads: 64
      type: bigquery
