answers: # to musi pasować do profilu w pliku dbt_project.yml
  target: dev # Domyślna opcja dla wszystkich poleceń dbt
  outputs:
    dev:
      type: bigquery
      # metoda: oauth
      method: service-account # Metoda uwierzytelniania - Service Account (dla GCP)
      keyfile: /Users/pmackowka/Documents/sa/dbt-project.json # Ścieżka do pliku klucza uwierzytelniającego

      # Aby użyć tej opcji, najpierw uruchom (w terminalu): export BIGQUERY_PROJECT="twoja_nazwa_projektu"
      # Następnie dbt rozpozna tę zmienną
      # database: "{{ env_var('BIGQUERY_PROJECT') }}"

      database: "coral-shift-440513-f3"
      schema: dbt_dev_answers # Schema, w której dbt ma tworzyć tabele
      threads: 64 # Maksymalna liczba równoczesnych procesów
      timeout_seconds: 300
      location: US
      priority: interactive # BigQuery może używać opcji "batch" lub "interactive". https://cloud.google.com/bigquery/docs/running-queries
      maximum_bytes_billed: 1000000000  # Limit 1 GB na zapytanie

    # Nie będziesz tego używać, ale jest to przykład użycia innego celu
    production:
      type: bigquery
      # metoda: oauth
      method: service-account # Metoda uwierzytelniania - Service Account (dla GCP)
      keyfile: /Users/pmackowka/Documents/sa/dbt-project.json # Ścieżka do pliku klucza uwierzytelniającego
      database: "coral-shift-440513-f3"
      schema: dbt_production
      threads: 64
      timeout_seconds: 300
      location: US
      priority: interactive
      maximum_bytes_billed: 1000000000  # Limit 1 GB na zapytanie