dbt_ga4_velir:
  target: dev
  outputs:
    dev:
      dataset: project_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/pmackowka/Documents/sa/avon-prod-analytics.json
      location: EU
      method: service-account
      priority: interactive
      project: avon-prod-analytics
      threads: 64
      type: bigquery

    prod:
      dataset: project_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/pmackowka/Documents/sa/avon-prod-analytics.json
      location: EU
      method: service-account
      priority: interactive
      project: avon-prod-analytics
      threads: 64
      type: bigquery
