lessons: # Nazwa konfiguracji. Musi odpowiadać wartości `profile:` w pliku `dbt_project.yml`
  target: dev # Domyślny cel (środowisko) dla poleceń dbt, tutaj: "dev" (środowisko deweloperskie)
  outputs: # Definicja różnych konfiguracji połączenia
    dev: # Konfiguracja środowiska deweloperskiego
      type: bigquery # Określenie silnika bazodanowego - tutaj BigQuery
      # method: oauth # Metoda uwierzytelniania - OAuth (domyślnie dla GCP)
      method: service-account # Metoda uwierzytelniania - Service Account (dla GCP)
      keyfile: /Users/pmackowka/Documents/sa/dbt-project.json # Ścieżka do pliku klucza uwierzytelniającego

      # Ustawienie dynamicznej wartości dla projektu BigQuery poprzez zmienną środowiskową
      # Przed uruchomieniem dbt, należy wykonać w terminalu:
      # export BIGQUERY_PROJECT="nazwa_twojego_projektu"
      database: "{{ env_var('BIGQUERY_PROJECT') }}"

      schema: dbt_test # Nazwa schematu w BigQuery. Powinna być zmieniona na unikalną, np. "dbt_towje_imie"

      threads: 64 # Maksymalna liczba równocześnie wykonywanych operacji (zalecane: dostosowanie do zasobów)
      timeout_seconds: 300 # Maksymalny czas oczekiwania na wykonanie zapytania w sekundach
      location: US # Lokalizacja danych w BigQuery (np. "EU" dla europejskich regionów)

      priority: interactive # Tryb przetwarzania zapytań:
                           # "interactive" dla natychmiastowego wykonania
                           # "batch" dla tańszego, ale wolniejszego przetwarzania

      maximum_bytes_billed: 1000000000 # Limit rozliczeniowy dla zapytań w bajtach (~0.93 GB)

    # Przykładowa konfiguracja środowiska produkcyjnego (niewykorzystywana w tym kursie)
    production:
      type: bigquery
      # method: oauth
      method: service-account # Metoda uwierzytelniania - Service Account (dla GCP)
      keyfile: /Users/pmackowka/Documents/sa/dbt-project.json # Ścieżka do pliku klucza uwierzytelniającego
      database: "{{ env_var('BIGQUERY_PROJECT') }}"
      schema: dbt_production # Schemat produkcyjny zamiast testowego
      threads: 64
      timeout_seconds: 300
      location: US
      priority: interactive
      maximum_bytes_billed: 1000000000 # Limit rozliczeniowy, taki sam jak dla "dev"