answers: # this needs to match the profile: in your dbt_project.yml file
  target: dev # The default for any dbt commands
  outputs:
    dev:
      type: bigquery
      # method: oauth
      method: service-account # Metoda uwierzytelniania - Service Account (dla GCP)
      keyfile: /Users/pmackowka/Documents/sa/dbt-project.json # Ścieżka do pliku klucza uwierzytelniającego
      # To use this, first run (in your terminal): export BIGQUERY_PROJECT="your_project_name"
      # Then dbt will recognise the variable
      database: "{{ env_var('BIGQUERY_PROJECT') }}"
      schema: dbt_test # Replace this with dbt_your_name, e.g. dbt_bob
      threads: 64 # Max number of concurrent things running at once
      timeout_seconds: 300
      location: US
      priority: interactive # BigQuery can use "batch" or "interactive". https://cloud.google.com/bigquery/docs/running-queries
      maximum_bytes_billed: 1000000000  # Limit 1 GB na zapytanie

    # You won't use this, but an example of using a different target
    production:
      type: bigquery
      # method: oauth
      method: service-account # Metoda uwierzytelniania - Service Account (dla GCP)
      keyfile: /Users/pmackowka/Documents/sa/dbt-project.json # Ścieżka do pliku klucza uwierzytelniającego
      database: "{{ env_var('BIGQUERY_PROJECT') }}"
      schema: dbt_production
      threads: 64
      timeout_seconds: 300
      location: US
      priority: interactive
      maximum_bytes_billed: 1000000000  # Limit 1 GB na zapytanie
